---
- name: Obter informações do sistema
  ansible.builtin.setup:
      
- name: Extrair informações relevantes
  set_fact:
    server_info:
      hostname: "{{ ansible_hostname }}"
      ip: "{{ ansible_host }}"
      cpu: "{{ ansible_processor_vcpus }}"
      memoria: "{{ ansible_memory_mb.real.total }}"
      disco: "{{ ansible_mounts | json_query('[*].{device: device, fstype: fstype, total: size_total_bytes, free: size_available_bytes }') }}"

- name: Criar arquivo CSV
  ansible.builtin.lineinfile:
    path: "/tmp/server_info.csv"
    create: yes
    line: "{{ server_info | to_nice_json }}"
  #delegate_to: localhost

...
